import type { Lang } from '../../../i18n/context'
import type { GroupId } from './balance.data'
import type { DreLineId } from './balance/balance.logic'

const ptAccounts: Record<string, string> = {
  '1': 'ATIVO',
  '1.1': 'Ativo Circulante',
  '1.1.01': 'Caixa e equivalentes',
  '1.1.01.001': 'Caixa geral',
  '1.1.01.002': 'Bancos conta movimento',
  '1.1.02': 'Clientes',
  '1.1.02.001': 'Duplicatas a receber',
  '1.1.02.002': '(−) Perdas estimadas',
  '1.1.03': 'Impostos a recuperar',
  '1.1.03.001': 'Impostos a recuperar',
  '1.2': 'Ativo Não Circulante',
  '1.2.01': 'Imobilizado',
  '1.2.01.001': 'Veículos',
  '1.2.01.002': 'Edificações',
  '1.2.01.003': '(−) Depreciação acumulada',
  '1.3': 'Outros ativos',
  '1.3.01': 'Depósitos e adiantamentos',
  '1.3.01.001': 'Depósitos judiciais',
  '1.3.01.002': 'Adiantamentos de longo prazo',
  '1.3.02': 'Intangível',
  '1.3.02.001': 'Software e licenças',
  '2': 'PASSIVO E PATRIMÔNIO LÍQUIDO',
  '2.1': 'Passivo Circulante',
  '2.1.01': 'Fornecedores',
  '2.1.01.001': 'Fornecedores nacionais',
  '2.1.01.002': 'Fretes a pagar',
  '2.1.02': 'Obrigações trabalhistas',
  '2.1.02.001': 'Salários a pagar',
  '2.1.02.002': 'Encargos sociais',
  '2.1.03': 'Obrigações fiscais',
  '2.1.03.001': 'Impostos a recolher',
  '2.2': 'Passivo Não Circulante',
  '2.2.01': 'Financiamentos',
  '2.2.01.001': 'Financiamento de veículos',
  '2.3': 'Patrimônio Líquido',
  '2.3.01': 'Capital social',
  '2.3.01.001': 'Capital subscrito',
  '2.3.02': 'Reservas e resultados',
  '2.3.02.001': 'Reservas de lucros',
  '2.3.02.002': 'Resultado do período',
  '3': 'RECEITAS',
  '3.1': 'Receita de fretes',
  '3.1.01': 'Receita operacional',
  '3.1.01.001': 'Fretes nacionais',
  '3.1.01.002': 'Fretes de transferência',
  '3.1.01.003': 'Serviços acessórios',
  '3.2': 'Deduções da receita',
  '3.2.01': 'Deduções',
  '3.2.01.001': 'Impostos sobre faturamento',
  '3.2.01.002': 'Devoluções e cancelamentos',
  '4': 'CUSTOS E DESPESAS',
  '4.1': 'Custos dos serviços',
  '4.1.01': 'Custos operacionais',
  '4.1.01.001': 'Combustível',
  '4.1.01.002': 'Pedágios',
  '4.1.01.003': 'Manutenção de frota',
  '4.1.01.004': 'Pessoal operacional',
  '4.2': 'Despesas operacionais',
  '4.2.01': 'Despesas gerais',
  '4.2.01.001': 'Despesas administrativas',
  '4.2.01.002': 'Despesas comerciais',
  '4.3': 'Resultado financeiro',
  '4.3.01': 'Financeiras',
  '4.3.01.001': 'Receitas financeiras',
  '4.3.01.002': 'Despesas financeiras',
  '4.4': 'Impostos sobre o lucro',
  '4.4.01': 'Provisões',
  '4.4.01.001': 'Provisão de IR e CSLL',
}

const enAccounts: Record<string, string> = {
  '1': 'ASSETS',
  '1.1': 'Current Assets',
  '1.1.01': 'Cash and equivalents',
  '1.1.01.001': 'Petty cash',
  '1.1.01.002': 'Bank accounts',
  '1.1.02': 'Customers',
  '1.1.02.001': 'Trade receivables',
  '1.1.02.002': '(−) Estimated losses',
  '1.1.03': 'Recoverable taxes',
  '1.1.03.001': 'Recoverable taxes',
  '1.2': 'Non-current Assets',
  '1.2.01': 'Property and equipment',
  '1.2.01.001': 'Vehicles',
  '1.2.01.002': 'Buildings',
  '1.2.01.003': '(−) Accumulated depreciation',
  '1.3': 'Other assets',
  '1.3.01': 'Deposits and advances',
  '1.3.01.001': 'Court deposits',
  '1.3.01.002': 'Long-term advances',
  '1.3.02': 'Intangible',
  '1.3.02.001': 'Software and licenses',
  '2': 'LIABILITIES AND EQUITY',
  '2.1': 'Current Liabilities',
  '2.1.01': 'Suppliers',
  '2.1.01.001': 'Domestic suppliers',
  '2.1.01.002': 'Freight payable',
  '2.1.02': 'Labor obligations',
  '2.1.02.001': 'Salaries payable',
  '2.1.02.002': 'Payroll charges',
  '2.1.03': 'Tax obligations',
  '2.1.03.001': 'Taxes payable',
  '2.2': 'Non-current Liabilities',
  '2.2.01': 'Financing',
  '2.2.01.001': 'Vehicle financing',
  '2.3': 'Equity',
  '2.3.01': 'Share capital',
  '2.3.01.001': 'Subscribed capital',
  '2.3.02': 'Reserves and results',
  '2.3.02.001': 'Profit reserves',
  '2.3.02.002': 'Result for the period',
  '3': 'REVENUE',
  '3.1': 'Freight revenue',
  '3.1.01': 'Operating revenue',
  '3.1.01.001': 'Domestic freight',
  '3.1.01.002': 'Transfer freight',
  '3.1.01.003': 'Ancillary services',
  '3.2': 'Revenue deductions',
  '3.2.01': 'Deductions',
  '3.2.01.001': 'Taxes on billing',
  '3.2.01.002': 'Returns and cancellations',
  '4': 'COSTS AND EXPENSES',
  '4.1': 'Cost of services',
  '4.1.01': 'Operating costs',
  '4.1.01.001': 'Fuel',
  '4.1.01.002': 'Tolls',
  '4.1.01.003': 'Fleet maintenance',
  '4.1.01.004': 'Operating staff',
  '4.2': 'Operating expenses',
  '4.2.01': 'General expenses',
  '4.2.01.001': 'Administrative expenses',
  '4.2.01.002': 'Sales expenses',
  '4.3': 'Financial result',
  '4.3.01': 'Financial',
  '4.3.01.001': 'Financial income',
  '4.3.01.002': 'Financial expenses',
  '4.4': 'Income taxes',
  '4.4.01': 'Provisions',
  '4.4.01.001': 'Income tax provision',
}

const pt = {
  brand: 'Contábil',
  nav: { statements: 'Demonstrações', closing: 'Fechamentos', settings: 'Configurações' },
  user: 'Controladoria',
  accounts: ptAccounts,
  groups: {
    ativoCirc: 'Ativo Circulante',
    ativoNaoCirc: 'Ativo Não Circulante',
    passivoCirc: 'Passivo Circulante',
    passivoNaoCirc: 'Passivo Não Circulante',
    patrimonio: 'Patrimônio Líquido',
    receita: 'Receita bruta',
    deducoes: 'Deduções',
    custos: 'Custos dos serviços',
    despesas: 'Despesas operacionais',
    financeiro: 'Resultado financeiro',
    impostos: 'IR e CSLL',
  } satisfies Record<GroupId, string>,
  months: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
  monthLabel: 'Mês',
  monthFull: (m: string) => `${m}/2026`,
  units: 'Valores em R$ mil · fictícios',
  tree: {
    title: 'Plano de contas',
    synthetic: 'Sintética',
    analytic: 'Analítica',
    unmapped: 'Sem grupo',
    inherited: 'herdado',
    map: 'Mapear nó',
    mapTo: 'Grupo de relatório',
    choose: 'Escolha…',
    apply: 'Aplicar',
    cancel: 'Cancelar',
    expand: (name: string) => `Expandir ${name}`,
    collapse: (name: string) => `Recolher ${name}`,
    inherit: (n: number) => (n === 1 ? '1 conta herdou' : `${n} contas herdaram`),
    toast: (code: string, group: string, n: number) =>
      `${code} mapeado para ${group}: ${n === 1 ? '1 conta herdou' : `${n} contas herdaram`} o grupo`,
  },
  tabs: {
    plan: 'Plano',
    balance: 'Balanço',
    dre: 'DRE',
    check: 'Conferência',
    label: 'Demonstrações',
  },
  balance: {
    assets: 'Ativo',
    liabilities: 'Passivo + PL',
    totalAssets: 'Total do Ativo',
    totalLiabilities: 'Total do Passivo + PL',
    closes: 'fecha ✓',
    difference: (v: string) => `diferença ${v}`,
    hint: 'Contas de nós sem grupo ficam fora do Balanço até serem mapeadas.',
  },
  dre: {
    line: 'Linha',
    month: 'Mês',
    ytd: 'Acumulado',
    lines: {
      receita: 'Receita bruta',
      deducoes: '(−) Deduções',
      liquida: '= Receita líquida',
      custos: '(−) Custos dos serviços',
      bruto: '= Lucro bruto',
      despesas: '(−) Despesas operacionais',
      operacional: '= Resultado operacional',
      financeiro: '(+/−) Resultado financeiro',
      antesIr: '= Resultado antes do IR',
      impostos: '(−) IR e CSLL',
      liquido: '= Lucro líquido',
    } satisfies Record<DreLineId, string>,
  },
  check: {
    title: 'Divergências',
    none: 'Nenhuma divergência',
    noneText: 'Todos os nós do plano têm grupo e o Balanço fecha.',
    unmappedItem: (code: string, name: string, n: number, value: string) =>
      `Nó ${code} ${name} sem grupo: ${n} contas (${value}) fora do Balanço`,
    goMap: 'Mapear',
    checksTitle: 'Verificações',
    balanceCheck: 'Ativo = Passivo + PL',
    dreCheck: 'Resultado da DRE = Resultado do período no PL',
    nodesCheck: 'Todos os nós têm grupo',
    ok: 'ok',
    fail: 'diverge',
  },
}

const en: typeof pt = {
  brand: 'Accounting',
  nav: { statements: 'Statements', closing: 'Closings', settings: 'Settings' },
  user: 'Controllership',
  accounts: enAccounts,
  groups: {
    ativoCirc: 'Current Assets',
    ativoNaoCirc: 'Non-current Assets',
    passivoCirc: 'Current Liabilities',
    passivoNaoCirc: 'Non-current Liabilities',
    patrimonio: 'Equity',
    receita: 'Gross revenue',
    deducoes: 'Deductions',
    custos: 'Cost of services',
    despesas: 'Operating expenses',
    financeiro: 'Financial result',
    impostos: 'Income taxes',
  },
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  monthLabel: 'Month',
  monthFull: (m) => `${m} 2026`,
  units: 'Amounts in R$ thousand · fictitious',
  tree: {
    title: 'Chart of accounts',
    synthetic: 'Synthetic',
    analytic: 'Analytic',
    unmapped: 'No group',
    inherited: 'inherited',
    map: 'Map node',
    mapTo: 'Report group',
    choose: 'Choose…',
    apply: 'Apply',
    cancel: 'Cancel',
    expand: (name) => `Expand ${name}`,
    collapse: (name) => `Collapse ${name}`,
    inherit: (n) => (n === 1 ? '1 account inherited' : `${n} accounts inherited`),
    toast: (code, group, n) =>
      `${code} mapped to ${group}: ${n === 1 ? '1 account' : `${n} accounts`} inherited the group`,
  },
  tabs: {
    plan: 'Chart',
    balance: 'Balance sheet',
    dre: 'Income statement',
    check: 'Checks',
    label: 'Statements',
  },
  balance: {
    assets: 'Assets',
    liabilities: 'Liabilities + Equity',
    totalAssets: 'Total assets',
    totalLiabilities: 'Total liabilities + equity',
    closes: 'balanced ✓',
    difference: (v) => `difference ${v}`,
    hint: 'Accounts under nodes without a group stay out of the balance sheet until mapped.',
  },
  dre: {
    line: 'Line',
    month: 'Month',
    ytd: 'Year to date',
    lines: {
      receita: 'Gross revenue',
      deducoes: '(−) Deductions',
      liquida: '= Net revenue',
      custos: '(−) Cost of services',
      bruto: '= Gross profit',
      despesas: '(−) Operating expenses',
      operacional: '= Operating result',
      financeiro: '(+/−) Financial result',
      antesIr: '= Result before income tax',
      impostos: '(−) Income taxes',
      liquido: '= Net income',
    },
  },
  check: {
    title: 'Divergences',
    none: 'No divergences',
    noneText: 'Every node in the chart has a group and the balance sheet balances.',
    unmappedItem: (code, name, n, value) =>
      `Node ${code} ${name} has no group: ${n} accounts (${value}) are out of the balance sheet`,
    goMap: 'Map',
    checksTitle: 'Checks',
    balanceCheck: 'Assets = Liabilities + Equity',
    dreCheck: 'Income statement result = period result in equity',
    nodesCheck: 'Every node has a group',
    ok: 'ok',
    fail: 'diverges',
  },
}

export const balanceCopy: Record<Lang, typeof pt> = { pt, en }
