import type { Lang } from '../../../i18n/context'
import type { QuoteStatus, ReasonId } from './crm.data'

const pt = {
  brand: 'CRM de Cotações',
  user: 'Comercial 03',
  nav: { queue: 'Fila', analysis: 'Análise' },
  status: { COTADO: 'Cotado', CANCELADA: 'Cancelada', CONTRATADA: 'Contratada' } satisfies Record<
    QuoteStatus,
    string
  >,
  reasons: {
    price: 'Preço',
    deadline: 'Prazo',
    noReply: 'Sem retorno do cliente',
    clientCancelled: 'Cancelado pelo cliente',
    competitor: 'Fechou com concorrente',
    capacity: 'Sem capacidade de frota',
  } satisfies Record<ReasonId, string>,
  tabs: { label: 'Cotações', pending: 'Pendentes', handled: 'Tratadas' },
  columns: {
    id: 'Cotação',
    client: 'Cliente',
    path: 'Trecho',
    value: 'Valor',
    status: 'Situação',
    idle: 'Dias parada',
    reason: 'Motivo',
    unit: 'Unidade',
  },
  idle: (n: number) => `${n} d`,
  queueTable: 'Cotações pendentes de tratativa',
  handledTable: 'Cotações tratadas',
  drawer: {
    title: 'Registrar tratativa',
    reason: 'Motivo',
    choose: 'Escolha o motivo…',
    note: 'Observação',
    notePlaceholder: 'O que foi combinado com o cliente?',
    save: 'Salvar tratativa',
    errorReason: 'Escolha um motivo para salvar.',
  },
  toastSaved: (id: string) => `Tratativa de ${id} registrada`,
  emptyQueue: 'Fila zerada',
  emptyQueueText: 'Todas as cotações receberam uma tratativa.',
  emptyHandled: 'Nenhuma tratativa ainda',
  analysis: {
    reasonsChart: 'Cotações por motivo',
    unitsChart: 'Cotações por unidade',
    hint: 'Clique em uma barra para filtrar o outro gráfico e a tabela.',
    clear: 'limpar filtro',
    filterReason: (r: string) => `Motivo: ${r}`,
    filterUnit: (u: string) => `Unidade: ${u}`,
    detail: (n: number) => `Detalhe · ${n} ${n === 1 ? 'cotação' : 'cotações'}`,
    total: (value: string) => `Total ${value}`,
  },
}

const en: typeof pt = {
  brand: 'Quote CRM',
  user: 'Sales 03',
  nav: { queue: 'Queue', analysis: 'Analysis' },
  status: { COTADO: 'Quoted', CANCELADA: 'Cancelled', CONTRATADA: 'Booked' },
  reasons: {
    price: 'Price',
    deadline: 'Lead time',
    noReply: 'No reply from customer',
    clientCancelled: 'Cancelled by customer',
    competitor: 'Went with a competitor',
    capacity: 'No fleet capacity',
  },
  tabs: { label: 'Quotes', pending: 'Pending', handled: 'Handled' },
  columns: {
    id: 'Quote',
    client: 'Customer',
    path: 'Path',
    value: 'Value',
    status: 'Status',
    idle: 'Days idle',
    reason: 'Reason',
    unit: 'Unit',
  },
  idle: (n) => `${n} d`,
  queueTable: 'Quotes pending follow-up',
  handledTable: 'Handled quotes',
  drawer: {
    title: 'Log follow-up',
    reason: 'Reason',
    choose: 'Choose the reason…',
    note: 'Note',
    notePlaceholder: 'What was agreed with the customer?',
    save: 'Save follow-up',
    errorReason: 'Choose a reason to save.',
  },
  toastSaved: (id) => `Follow-up for ${id} logged`,
  emptyQueue: 'Queue cleared',
  emptyQueueText: 'Every quote has a follow-up.',
  emptyHandled: 'No follow-ups yet',
  analysis: {
    reasonsChart: 'Quotes by reason',
    unitsChart: 'Quotes by unit',
    hint: 'Click a bar to filter the other chart and the table.',
    clear: 'clear filter',
    filterReason: (r) => `Reason: ${r}`,
    filterUnit: (u) => `Unit: ${u}`,
    detail: (n) => `Detail · ${n} ${n === 1 ? 'quote' : 'quotes'}`,
    total: (value) => `Total ${value}`,
  },
}

export const crmCopy: Record<Lang, typeof pt> = { pt, en }
