import type { Lang } from '../../../i18n/context'
import type { TitleStatus } from './payments.data'

const pt = {
  brand: 'Pagamentos',
  user: 'Analista financeiro',
  nav: { titles: 'Títulos em aberto', accounts: 'Contas bancárias' },
  status: {
    open: 'Aberto',
    advance: 'Adiantamento abatido',
    cancelled: 'Cancelado',
  } satisfies Record<TitleStatus, string>,
  kpi: {
    open: 'Em aberto',
    openHint: (n: number) => `${n} títulos`,
    advances: 'Adiantamentos abatidos',
    advancesHint: (n: number) => `${n} títulos`,
    suppliers: 'Fornecedores',
    suppliersHint: 'com título na lista',
  },
  showCancelled: 'mostrar cancelados',
  table: 'Títulos em aberto',
  columns: {
    supplier: 'Fornecedor',
    doc: 'Documento',
    installment: 'Parcela',
    due: 'Vencimento',
    amount: 'Valor a pagar',
    status: 'Situação',
  },
  advanceNote: (v: string) => `− ${v} de adiantamento`,
  summary: (n: number, total: string) => `${n} ${n === 1 ? 'título' : 'títulos'} · ${total}`,
  none: 'Nenhum título selecionado',
  clear: 'Limpar',
  generate: 'Gerar folha',
  sheet: {
    title: 'Dados para depósito',
    doc: 'DADOS PARA DEPÓSITO',
    issued: (d: string) => `Emissão ${d}`,
    supplier: 'Fornecedor',
    bank: 'Banco',
    agency: 'Agência',
    account: 'Conta',
    titles: 'Títulos',
    total: 'Valor',
    grand: 'Total geral',
    principal: 'conta principal',
    sendMail: 'Enviar por e-mail',
    sending: (done: number, total: number) => `${done} de ${total} enviados`,
    sent: 'Enviado',
    finished: (n: number) => `${n} e-mails enviados`,
    close: 'Fechar',
    note: 'Prévia da folha em PDF. Agência e conta aparecem mascaradas na demonstração.',
    progress: 'Envio por e-mail',
    pending: 'na fila',
  },
  accounts: {
    title: 'Contas bancárias',
    lede: 'Cada fornecedor pode ter várias contas; a principal é a que vai na folha.',
    count: (n: number) => `${n} ${n === 1 ? 'conta' : 'contas'}`,
    principal: 'principal',
    setPrincipal: (bank: string) => `Definir ${bank} como conta principal`,
    isPrincipal: (bank: string) => `${bank} é a conta principal`,
    toast: (supplier: string) => `Conta principal de ${supplier} atualizada`,
  },
}

const en: typeof pt = {
  brand: 'Payments',
  user: 'Finance analyst',
  nav: { titles: 'Open invoices', accounts: 'Bank accounts' },
  status: {
    open: 'Open',
    advance: 'Advance deducted',
    cancelled: 'Cancelled',
  },
  kpi: {
    open: 'Open',
    openHint: (n) => `${n} invoices`,
    advances: 'Advances deducted',
    advancesHint: (n) => `${n} invoices`,
    suppliers: 'Suppliers',
    suppliersHint: 'with an invoice listed',
  },
  showCancelled: 'show cancelled',
  table: 'Open invoices',
  columns: {
    supplier: 'Supplier',
    doc: 'Document',
    installment: 'Installment',
    due: 'Due date',
    amount: 'Amount to pay',
    status: 'Status',
  },
  advanceNote: (v) => `− ${v} advance`,
  summary: (n, total) => `${n} ${n === 1 ? 'invoice' : 'invoices'} · ${total}`,
  none: 'No invoice selected',
  clear: 'Clear',
  generate: 'Generate sheet',
  sheet: {
    title: 'Deposit details',
    doc: 'DEPOSIT DETAILS',
    issued: (d) => `Issued ${d}`,
    supplier: 'Supplier',
    bank: 'Bank',
    agency: 'Branch',
    account: 'Account',
    titles: 'Invoices',
    total: 'Amount',
    grand: 'Grand total',
    principal: 'primary account',
    sendMail: 'Send by email',
    sending: (done, total) => `${done} of ${total} sent`,
    sent: 'Sent',
    finished: (n) => `${n} emails sent`,
    close: 'Close',
    note: 'Preview of the PDF sheet. Branch and account are masked in the demo.',
    progress: 'Email dispatch',
    pending: 'queued',
  },
  accounts: {
    title: 'Bank accounts',
    lede: 'Each supplier can have several accounts; the primary one goes on the sheet.',
    count: (n) => `${n} ${n === 1 ? 'account' : 'accounts'}`,
    principal: 'primary',
    setPrincipal: (bank) => `Set ${bank} as primary account`,
    isPrincipal: (bank) => `${bank} is the primary account`,
    toast: (supplier) => `Primary account of ${supplier} updated`,
  },
}

export const paymentsCopy: Record<Lang, typeof pt> = { pt, en }
