import type { Lang } from '../../../i18n/context'
import type { Actor, RouteStatus, StopOp } from './routes.data'

const pt = {
  brand: 'Gestão de Rotas',
  roles: { regional: 'Regional Sul', manager: 'Gestor de rotas' },
  nav: { routes: 'Rotas', requests: 'Solicitações' },
  status: { active: 'Ativa', pending: 'Em aprovação', suspended: 'Suspensa' } satisfies Record<
    RouteStatus,
    string
  >,
  all: 'Todas',
  filterStatus: 'Filtrar por situação',
  searchLabel: 'Buscar rota',
  routesTable: 'Rotas cadastradas',
  columns: {
    code: 'Código',
    path: 'Trecho',
    days: 'Dias',
    vehicle: 'Conjunto',
    status: 'Situação',
  },
  days: {
    short: ['S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
    long: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'],
    label: (names: string) => `Dias de operação: ${names}`,
  },
  ops: { load: 'Carga', unload: 'Descarga', pass: 'Passagem' } satisfies Record<StopOp, string>,
  map: {
    caption: 'mapa esquemático · fora de escala',
    overview: 'Rotas ativas no mapa esquemático',
    route: (id: string, path: string) => `Mapa da rota ${id}: ${path}`,
    stop: (n: number, code: string, offset: number, time: string) =>
      `Parada ${n}: ${code}, D+${offset} às ${time}`,
  },
  drawer: {
    tabs: { periods: 'Vigências', stops: 'Paradas', history: 'Histórico' },
    tabsLabel: 'Detalhes da rota',
    current: 'vigente',
    since: 'desde',
    stopsCount: (n: number) => `${n} paradas`,
    stopN: (n: number) => `Parada ${n}`,
    request: 'Solicitar alteração',
    pendingHint: 'Já existe uma solicitação em análise para esta rota.',
    managerHint:
      'Perfil Gestor: as alterações chegam em Solicitações. Para pedir uma alteração, use o perfil Regional.',
    sentTitle: (id: string) => `Solicitação enviada: ${id} está em aprovação`,
    sentText: 'O Gestor compara o antes e o depois e aprova ou recusa.',
    goManager: 'Trocar para Gestor e revisar',
    version: (n: number) => `v${n}`,
    periodRange: (from: string, to: string | null, now: string) => `${from} → ${to ?? now}`,
  },
  periodNotes: {
    initial: 'Vigência inicial',
    adjust: 'Ajuste de horários de saída',
    change: 'Alteração aprovada',
  },
  history: {
    created: 'Rota cadastrada',
    submitted: 'Alteração solicitada',
    approved: 'Alteração aprovada',
    rejected: 'Alteração recusada',
    suspended: 'Rota suspensa',
  },
  actors: {
    regional: 'Regional Sul',
    manager: 'Gestor de rotas',
    system: 'Sistema',
  } satisfies Record<Actor, string>,
  form: {
    title: 'Solicitar alteração',
    intro: 'Preencha só o que muda. O Gestor verá o antes e o depois.',
    timeSection: 'Horário de uma parada',
    stop: 'Parada',
    newTime: 'Novo horário',
    daySection: 'Dia de operação',
    addDay: 'Adicionar dia',
    none: 'Nenhum',
    stopSection: 'Nova parada',
    node: 'Unidade',
    after: 'Depois da parada',
    stopTime: 'Horário',
    note: 'Justificativa',
    notePlaceholder: 'Ex.: ajuste para acompanhar a janela de descarga',
    cancel: 'Cancelar',
    send: 'Enviar',
    errorEmpty: 'Informe ao menos uma alteração.',
    fullWeek: 'A rota já opera todos os dias.',
  },
  changes: {
    stopLine: (n: number, code: string, time: string) => `Parada ${n} · ${code} · ${time}`,
    daysLine: 'Dias',
    newStop: (n: number, code: string, offset: number, time: string) =>
      `Nova parada ${n} · ${code} · D+${offset} ${time}`,
    time: (n: number, code: string) => `Horário da parada ${n} (${code})`,
    day: (name: string) => `Adiciona ${name}`,
    stop: (code: string, time: string) => `Nova parada ${code} às ${time}`,
  },
  requests: {
    title: 'Solicitações',
    empty: 'Nenhuma solicitação',
    emptyText: 'Peça uma alteração numa rota com o perfil Regional para ela chegar aqui.',
    by: (role: string, date: string) => `${role} · ${date}`,
    pending: 'Aguardando decisão',
    approved: 'Aprovada',
    rejected: 'Recusada',
    approve: 'Aprovar',
    reject: 'Recusar',
    waiting: 'Aguardando aprovação do Gestor.',
    viewRoute: 'Ver rota',
    before: 'Antes',
    after: 'Depois',
    note: 'Justificativa',
    diffSr: { del: 'removido', add: 'adicionado' },
    toastApproved: (id: string, version: number) => `Nova vigência v${version} criada em ${id}`,
    toastRejected: (id: string) =>
      `Solicitação de ${id} recusada; a rota voltou à situação anterior`,
    toastSent: (id: string) => `Solicitação enviada para ${id}`,
    decidedSection: 'Decididas',
    pendingSection: 'Pendentes',
  },
}

const en: typeof pt = {
  brand: 'Route Management',
  roles: { regional: 'South regional', manager: 'Route manager' },
  nav: { routes: 'Routes', requests: 'Requests' },
  status: { active: 'Active', pending: 'Pending approval', suspended: 'Suspended' },
  all: 'All',
  filterStatus: 'Filter by status',
  searchLabel: 'Search route',
  routesTable: 'Registered routes',
  columns: { code: 'Code', path: 'Path', days: 'Days', vehicle: 'Vehicle set', status: 'Status' },
  days: {
    short: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    long: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    label: (names) => `Operating days: ${names}`,
  },
  ops: { load: 'Loading', unload: 'Unloading', pass: 'Pass-through' },
  map: {
    caption: 'schematic map · not to scale',
    overview: 'Active routes on the schematic map',
    route: (id, path) => `Map of route ${id}: ${path}`,
    stop: (n, code, offset, time) => `Stop ${n}: ${code}, D+${offset} at ${time}`,
  },
  drawer: {
    tabs: { periods: 'Validity', stops: 'Stops', history: 'History' },
    tabsLabel: 'Route details',
    current: 'current',
    since: 'since',
    stopsCount: (n) => `${n} stops`,
    stopN: (n) => `Stop ${n}`,
    request: 'Request change',
    pendingHint: 'There is already a request under review for this route.',
    managerHint:
      'Manager role: changes arrive under Requests. To ask for a change, use the Regional role.',
    sentTitle: (id) => `Request sent: ${id} is pending approval`,
    sentText: 'The manager compares before and after, then approves or rejects.',
    goManager: 'Switch to Manager and review',
    version: (n) => `v${n}`,
    periodRange: (from, to, now) => `${from} → ${to ?? now}`,
  },
  periodNotes: {
    initial: 'Initial validity',
    adjust: 'Departure time adjustment',
    change: 'Approved change',
  },
  history: {
    created: 'Route registered',
    submitted: 'Change requested',
    approved: 'Change approved',
    rejected: 'Change rejected',
    suspended: 'Route suspended',
  },
  actors: { regional: 'South regional', manager: 'Route manager', system: 'System' },
  form: {
    title: 'Request change',
    intro: 'Fill in only what changes. The manager will see before and after.',
    timeSection: 'Time of a stop',
    stop: 'Stop',
    newTime: 'New time',
    daySection: 'Operating day',
    addDay: 'Add day',
    none: 'None',
    stopSection: 'New stop',
    node: 'Unit',
    after: 'After stop',
    stopTime: 'Time',
    note: 'Reason',
    notePlaceholder: 'E.g. adjust to match the unloading window',
    cancel: 'Cancel',
    send: 'Submit',
    errorEmpty: 'Enter at least one change.',
    fullWeek: 'The route already runs every day.',
  },
  changes: {
    stopLine: (n, code, time) => `Stop ${n} · ${code} · ${time}`,
    daysLine: 'Days',
    newStop: (n, code, offset, time) => `New stop ${n} · ${code} · D+${offset} ${time}`,
    time: (n, code) => `Time of stop ${n} (${code})`,
    day: (name) => `Adds ${name}`,
    stop: (code, time) => `New stop ${code} at ${time}`,
  },
  requests: {
    title: 'Requests',
    empty: 'No requests',
    emptyText: 'Ask for a change on a route with the Regional role and it will show up here.',
    by: (role, date) => `${role} · ${date}`,
    pending: 'Awaiting decision',
    approved: 'Approved',
    rejected: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    waiting: 'Awaiting manager approval.',
    viewRoute: 'View route',
    before: 'Before',
    after: 'After',
    note: 'Reason',
    diffSr: { del: 'removed', add: 'added' },
    toastApproved: (id, version) => `New validity v${version} created on ${id}`,
    toastRejected: (id) => `Request for ${id} rejected; the route went back to its previous status`,
    toastSent: (id) => `Request sent for ${id}`,
    decidedSection: 'Decided',
    pendingSection: 'Pending',
  },
}

export const routesCopy: Record<Lang, typeof pt> = { pt, en }
